name: Release

on:
  push:
    tags: ["*"]

permissions:
    contents: write
    id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make a release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true